//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: RiderTestsSupportPlusModel.kt:11</p>
  /// </summary>
  public class RiderTestsSupportPlusModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<SaveSessionRequest, int> SaveSession => _SaveSession;
    [NotNull] public IRdEndpoint<string, SessionReport> LoadSession => _LoadSession;
    [NotNull] public IRdEndpoint<string, SessionReport> ImportRunSettings => _ImportRunSettings;
    
    //private fields
    [NotNull] private readonly RdCall<SaveSessionRequest, int> _SaveSession;
    [NotNull] private readonly RdCall<string, SessionReport> _LoadSession;
    [NotNull] private readonly RdCall<string, SessionReport> _ImportRunSettings;
    
    //primary constructor
    private RiderTestsSupportPlusModel(
      [NotNull] RdCall<SaveSessionRequest, int> saveSession,
      [NotNull] RdCall<string, SessionReport> loadSession,
      [NotNull] RdCall<string, SessionReport> importRunSettings
    )
    {
      if (saveSession == null) throw new ArgumentNullException("saveSession");
      if (loadSession == null) throw new ArgumentNullException("loadSession");
      if (importRunSettings == null) throw new ArgumentNullException("importRunSettings");
      
      _SaveSession = saveSession;
      _LoadSession = loadSession;
      _ImportRunSettings = importRunSettings;
      BindableChildren.Add(new KeyValuePair<string, object>("saveSession", _SaveSession));
      BindableChildren.Add(new KeyValuePair<string, object>("loadSession", _LoadSession));
      BindableChildren.Add(new KeyValuePair<string, object>("importRunSettings", _ImportRunSettings));
    }
    //secondary constructor
    internal RiderTestsSupportPlusModel (
    ) : this (
      new RdCall<SaveSessionRequest, int>(SaveSessionRequest.Read, SaveSessionRequest.Write, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdCall<string, SessionReport>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, SessionReport.Read, SessionReport.Write),
      new RdCall<string, SessionReport>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, SessionReport.Read, SessionReport.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -4442246916081668415L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("RiderTestsSupportPlusModel (");
      using (printer.IndentCookie()) {
        printer.Print("saveSession = "); _SaveSession.PrintEx(printer); printer.Println();
        printer.Print("loadSession = "); _LoadSession.PrintEx(printer); printer.Println();
        printer.Print("importRunSettings = "); _ImportRunSettings.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionRiderTestsSupportPlusModelEx
   {
    public static RiderTestsSupportPlusModel GetRiderTestsSupportPlusModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("riderTestsSupportPlusModel", () => new RiderTestsSupportPlusModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RiderTestsSupportPlusModel.kt:24</p>
  /// </summary>
  public sealed class SaveSessionRequest : IPrintable, IEquatable<SaveSessionRequest>
  {
    //fields
    //public fields
    [CanBeNull] public string SessionName {get; private set;}
    [NotNull] public string Path {get; private set;}
    
    //private fields
    //primary constructor
    public SaveSessionRequest(
      [CanBeNull] string sessionName,
      [NotNull] string path
    )
    {
      if (path == null) throw new ArgumentNullException("path");
      
      SessionName = sessionName;
      Path = path;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([CanBeNull] out string sessionName, [NotNull] out string path)
    {
      sessionName = SessionName;
      path = Path;
    }
    //statics
    
    public static CtxReadDelegate<SaveSessionRequest> Read = (ctx, reader) => 
    {
      var sessionName = ReadStringNullable(ctx, reader);
      var path = reader.ReadString();
      var _result = new SaveSessionRequest(sessionName, path);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<SaveSessionRequest> Write = (ctx, writer, value) => 
    {
      WriteStringNullable(ctx, writer, value.SessionName);
      writer.Write(value.Path);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((SaveSessionRequest) obj);
    }
    public bool Equals(SaveSessionRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(SessionName, other.SessionName) && Path == other.Path;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + (SessionName != null ? SessionName.GetHashCode() : 0);
        hash = hash * 31 + Path.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("SaveSessionRequest (");
      using (printer.IndentCookie()) {
        printer.Print("sessionName = "); SessionName.PrintEx(printer); printer.Println();
        printer.Print("path = "); Path.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: RiderTestsSupportPlusModel.kt:13</p>
  /// </summary>
  public sealed class SessionReport : IPrintable, IEquatable<SessionReport>
  {
    //fields
    //public fields
    [CanBeNull] public string SessionName {get; private set;}
    [NotNull] public List<string> Exact {get; private set;}
    [NotNull] public List<string> Ancestors {get; private set;}
    [NotNull] public List<string> Unresolved {get; private set;}
    [NotNull] public List<string> Notes {get; private set;}
    public bool Rescanned {get; private set;}
    
    //private fields
    //primary constructor
    public SessionReport(
      [CanBeNull] string sessionName,
      [NotNull] List<string> exact,
      [NotNull] List<string> ancestors,
      [NotNull] List<string> unresolved,
      [NotNull] List<string> notes,
      bool rescanned
    )
    {
      if (exact == null) throw new ArgumentNullException("exact");
      if (ancestors == null) throw new ArgumentNullException("ancestors");
      if (unresolved == null) throw new ArgumentNullException("unresolved");
      if (notes == null) throw new ArgumentNullException("notes");
      
      SessionName = sessionName;
      Exact = exact;
      Ancestors = ancestors;
      Unresolved = unresolved;
      Notes = notes;
      Rescanned = rescanned;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([CanBeNull] out string sessionName, [NotNull] out List<string> exact, [NotNull] out List<string> ancestors, [NotNull] out List<string> unresolved, [NotNull] out List<string> notes, out bool rescanned)
    {
      sessionName = SessionName;
      exact = Exact;
      ancestors = Ancestors;
      unresolved = Unresolved;
      notes = Notes;
      rescanned = Rescanned;
    }
    //statics
    
    public static CtxReadDelegate<SessionReport> Read = (ctx, reader) => 
    {
      var sessionName = ReadStringNullable(ctx, reader);
      var exact = ReadStringList(ctx, reader);
      var ancestors = ReadStringList(ctx, reader);
      var unresolved = ReadStringList(ctx, reader);
      var notes = ReadStringList(ctx, reader);
      var rescanned = reader.ReadBool();
      var _result = new SessionReport(sessionName, exact, ancestors, unresolved, notes, rescanned);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<List<string>> ReadStringList = JetBrains.Rd.Impl.Serializers.ReadString.List();
    
    public static CtxWriteDelegate<SessionReport> Write = (ctx, writer, value) => 
    {
      WriteStringNullable(ctx, writer, value.SessionName);
      WriteStringList(ctx, writer, value.Exact);
      WriteStringList(ctx, writer, value.Ancestors);
      WriteStringList(ctx, writer, value.Unresolved);
      WriteStringList(ctx, writer, value.Notes);
      writer.Write(value.Rescanned);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<List<string>> WriteStringList = JetBrains.Rd.Impl.Serializers.WriteString.List();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((SessionReport) obj);
    }
    public bool Equals(SessionReport other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(SessionName, other.SessionName) && Exact.SequenceEqual(other.Exact) && Ancestors.SequenceEqual(other.Ancestors) && Unresolved.SequenceEqual(other.Unresolved) && Notes.SequenceEqual(other.Notes) && Rescanned == other.Rescanned;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + (SessionName != null ? SessionName.GetHashCode() : 0);
        hash = hash * 31 + Exact.ContentHashCode();
        hash = hash * 31 + Ancestors.ContentHashCode();
        hash = hash * 31 + Unresolved.ContentHashCode();
        hash = hash * 31 + Notes.ContentHashCode();
        hash = hash * 31 + Rescanned.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("SessionReport (");
      using (printer.IndentCookie()) {
        printer.Print("sessionName = "); SessionName.PrintEx(printer); printer.Println();
        printer.Print("exact = "); Exact.PrintEx(printer); printer.Println();
        printer.Print("ancestors = "); Ancestors.PrintEx(printer); printer.Println();
        printer.Print("unresolved = "); Unresolved.PrintEx(printer); printer.Println();
        printer.Print("notes = "); Notes.PrintEx(printer); printer.Println();
        printer.Print("rescanned = "); Rescanned.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
